[package]
name = "tracer_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.4.1"
contracts = "0.6.3"
color-backtrace = "0.6.1"

dotenv = "0.15.0"
log = "0.4.20"
env_logger = "0.10.1"

wgpu = "0.18.0"
winit = "0.28.0"

stuff = { path = "./thirdparty/stuff" }
